# Generated by Django 5.0.6 on 2024-07-25 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarriageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('S', 'Second class'), ('F', 'First class'), ('L', 'Lux class')], default='S', max_length=1)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('O', 'Ordinary'), ('H', 'High speed')], default='H', max_length=1)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SpotModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('B', 'Bottom'), ('T', 'Top'), ('S', 'Side')], default='B', max_length=1)),
                ('number', models.IntegerField()),
                ('carriage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railway.carriagemodel')),
            ],
        ),
        migrations.CreateModel(
            name='RoadmapModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_set', to='railway.stationmodel')),
                ('destination_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_set', to='railway.stationmodel')),
                ('train', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_train', to='railway.trainmodel')),
            ],
        ),
        migrations.CreateModel(
            name='RoadmapDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateTimeField()),
                ('arrival_date', models.DateTimeField()),
                ('roadmap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='railway.roadmapmodel')),
                ('departure_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_station_detail', to='railway.stationmodel')),
                ('destination_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_station_detail', to='railway.stationmodel')),
            ],
        ),
        migrations.AddField(
            model_name='carriagemodel',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railway.trainmodel'),
        ),
    ]
