# Generated by Django 5.0.6 on 2024-07-25 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_spot_set', to='railway.stationmodel')),
                ('destination_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_spot_set', to='railway.stationmodel')),
                ('spot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gfhgfh', to='railway.spotmodel')),
            ],
        ),
    ]
