# Generated by Django 5.0.6 on 2024-07-11 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0002_roadmapmodel_train_roadmapdetailmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadmapdetailmodel',
            name='roadmap',
        ),
        migrations.AddField(
            model_name='roadmapdetailmodel',
            name='roadmap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='railway.roadmapmodel'),
        ),
    ]
