# Generated by Django 5.0.6 on 2024-07-25 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0002_spotdetailmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotdetailmodel',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spot_detail', to='railway.spotmodel'),
        ),
    ]
