# Generated by Django 5.0.6 on 2024-07-24 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0003_remove_roadmapdetailmodel_roadmap_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carriagemodel',
            name='spot_numbers',
        ),
    ]
