# Generated by Django 5.0.6 on 2024-07-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0003_alter_spotdetailmodel_spot'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotdetailmodel',
            name='customer_id',
            field=models.IntegerField(null=True),
        ),
    ]
