services:
  user-service:
    build: ./backend/user_service
    ports:
      - "8001:8001"
    volumes:
      - ./backend/user_service:/code
    depends_on:
      - user-service-celery

  railway-service:
    build: ./backend/railway_service
    ports:
      - "8002:8002"
    volumes:
      - ./backend/railway_service:/code
    depends_on:
      - railway-service-celery

  api-gateway:
    build: ./backend/api_gateway
    ports:
      - "8000:8000"
    volumes:
      - ./backend/api_gateway:/code

  redis:
    image: redis
    ports:
      - "6379:6379"

  user-service-celery:
    build: ./backend/user_service
    command: celery -A user_service worker -l info
    depends_on:
      - redis

  railway-service-celery:
    build: ./backend/railway_service
    command: celery -A railway_service worker -l info
    depends_on:
      - redis