services:
  user-service:
    build: ./backend/user_service
    ports:
      - "8001:8001"
    env_file:
      - ./backend/user_service/.env
    networks:
      - my_network

  api-gateway:
    build: ./backend/api_gateway
    ports:
      - "8000:8000"
    env_file:
      - ./backend/api_gateway/.env
    networks:
      - my_network

networks:
  my_network:
    driver: bridge