services:
  user-service:
    build: ./backend/user_service
    ports:
      - "8001:8001"
    volumes:
      - ./backend/user_service:/code
    depends_on:
      - celery

  api-gateway:
    build: ./backend/api_gateway
    ports:
      - "8000:8000"
    volumes:
      - ./backend/api_gateway:/code

  redis:
    image: redis
    ports:
      - "6379:6379"

  celery:
    build: ./backend/user_service
    command: celery -A user_service worker -l info
    depends_on:
      - redis